(() => {
 'use strict';
 const {tracks,videos,scores}=window.MEDIA_DATA;
 const $=id=>document.getElementById(id);
 const lang=()=>document.documentElement.lang==='en'?'en':'ua';
 const tr=(ua,en)=>lang()==='en'?en:ua;
 const time=s=>`${Math.floor((Number(s)||0)/60)}:${String(Math.floor((Number(s)||0)%60)).padStart(2,'0')}`;
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const label=(node,ua,en)=>{node.dataset.ua=ua;node.dataset.en=en;node.textContent=tr(ua,en);return node;};
 const tabs=[...document.querySelectorAll('[data-tab]')],heading=$('media-heading');let active='listen',track=0,photoIndex=0,dialogOpener=null;
 const titles={listen:['Слухати','Listen'],videos:['Відео','Videos'],scores:['Ноти','Sheet Music'],photos:['Фото','Photos']};
 const audio=$('album-audio'),box=$('media-dialog');
 function stopDialog(){box.querySelectorAll('audio').forEach(a=>a.pause());$('dialog-content').replaceChildren();}
 function selectTab(key,updateHash=true){if(!titles[key])key='listen';active=key;tabs.forEach(b=>{const yes=b.dataset.tab===key;b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1;$('panel-'+b.dataset.tab).hidden=!yes;});[heading.dataset.ua,heading.dataset.en]=titles[key];heading.textContent=heading.dataset[lang()];document.title=heading.textContent+' | Yurij Budnik';if(key!=='listen')audio.pause();if(box.open)box.close();if(updateHash)history.replaceState(null,'','#'+key);}
 tabs.forEach(b=>{b.addEventListener('click',()=>selectTab(b.dataset.tab));b.addEventListener('keydown',e=>{const horizontal=window.innerWidth<768,forward=horizontal?'ArrowRight':'ArrowDown',back=horizontal?'ArrowLeft':'ArrowUp';let i=tabs.indexOf(b);if(e.key===forward)i=(i+1)%4;else if(e.key===back)i=(i+3)%4;else if(e.key==='Home')i=0;else if(e.key==='End')i=3;else return;e.preventDefault();tabs[i].focus();selectTab(tabs[i].dataset.tab);});});
 function renderControls(){const playing=!audio.paused;$('track-play').textContent=playing?'Ⅱ':'▶';$('track-play').setAttribute('aria-label',playing?tr('Пауза','Pause'):tr('Відтворити','Play'));$('now-playing').textContent=tracks[track].title;document.querySelectorAll('#track-list button').forEach((b,i)=>b.setAttribute('aria-current',String(i===track)));}
 function choose(i,play=false){track=(i+tracks.length)%tracks.length;audio.src=tracks[track].src;$('seek').value=0;$('elapsed').textContent='0:00';$('duration').textContent=time(tracks[track].duration);$('audio-status').textContent='';renderControls();if(play)playAudio();}
 async function playAudio(){try{await audio.play();}catch{if(audio.error)$('audio-status').textContent=tr('Не вдалося відкрити аудіофайл.','Could not load the audio file.');}renderControls();}
 tracks.forEach((t,i)=>{const li=el('li'),b=el('button');b.type='button';b.append(el('span','track-num',String(i+1).padStart(2,'0')),el('span','track-name',t.title),el('span','track-time',time(t.duration)));b.addEventListener('click',()=>{if(i===track&&!audio.paused)audio.pause();else choose(i,true);});li.append(b);$('track-list').append(li);});
 $('track-play').addEventListener('click',()=>audio.paused?playAudio():audio.pause());$('track-prev').addEventListener('click',()=>choose(track-1,true));$('track-next').addEventListener('click',()=>choose(track+1,true));$('volume').addEventListener('input',e=>audio.volume=+e.target.value);$('seek').addEventListener('input',e=>{if(Number.isFinite(audio.duration))audio.currentTime=audio.duration*(+e.target.value/1000);});
 audio.addEventListener('timeupdate',()=>{$('elapsed').textContent=time(audio.currentTime);if(audio.duration)$('seek').value=audio.currentTime/audio.duration*1000;});audio.addEventListener('loadedmetadata',()=>$('duration').textContent=time(audio.duration));audio.addEventListener('play',()=>{box.querySelectorAll('audio').forEach(a=>a.pause());renderControls();});audio.addEventListener('pause',renderControls);audio.addEventListener('ended',()=>choose(track+1,true));audio.addEventListener('error',()=>{$('audio-status').textContent=tr('Не вдалося відкрити аудіофайл.','Could not load the audio file.');});
 function openDialog(button){dialogOpener=button;audio.pause();if(!box.open){box.showModal();document.body.classList.add('photo-open');}$('dialog-close').focus();}
 function video(id,start,title,button){stopDialog();const h=el('h2',null,title),iframe=el('iframe');iframe.src=`https://www.youtube-nocookie.com/embed/${id}?start=${start||0}&autoplay=1`;iframe.title=title;iframe.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';iframe.allowFullscreen=true;const a=label(el('a'),'Відкрити на YouTube','Open on YouTube');a.href=`https://www.youtube.com/watch?v=${id}&t=${start||0}s`;a.target='_blank';a.rel='noopener';$('dialog-content').append(h,iframe,a);openDialog(button);}
 videos.forEach(v=>{const card=el('article','video-card'),b=el('button','video-thumb');b.type='button';const img=el('img');img.src=`https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`;img.alt='';img.loading='lazy';b.append(img,el('span','play-symbol','▶'),el('span','youtube-label','YouTube'));b.setAttribute('aria-label',v.titleUa);const h=label(el('h2'),v.titleUa,v.titleEn),a=label(el('a'),'Відкрити на YouTube','Open on YouTube');a.href=`https://www.youtube.com/watch?v=${v.id}&t=${v.start}s`;a.target='_blank';a.rel='noopener';b.addEventListener('click',()=>video(v.id,v.start,h.textContent,b));card.append(b,h,a);$('video-grid').append(card);});
 scores.forEach(s=>{const card=el('article','score-card'),preview=el('button','score-preview');preview.type='button';preview.setAttribute('aria-label',s.title);const img=el('img');img.src=s.preview;img.alt=s.title;img.loading='lazy';preview.append(img);preview.addEventListener('click',()=>{stopDialog();const large=el('img','viewer-img');large.src=s.preview;large.alt=s.title;$('dialog-content').append(el('h2',null,s.title),large);openDialog(preview);});const info=el('div','score-info');info.append(el('h2',null,s.title),label(el('p','score-meta'),`Для баяна · PDF · ${s.pages} стор.`,`For bayan · PDF · ${s.pages} pages`),el('p','score-price',`${s.price} USD`));const buy=label(el(s.buyUrl?'a':'button','buy-button'),'Купити ноти','Buy sheet music');if(s.buyUrl){buy.href=s.buyUrl;buy.target='_blank';buy.rel='noopener';}else{buy.type='button';buy.disabled=true;}info.append(buy);if(!s.buyUrl)info.append(label(el('p','purchase-pending'),'Незабаром у продажу','Coming soon'));const actions=el('div','score-actions'),ab=label(el('button'),'♫ Аудіо','♫ Audio'),vb=label(el('button'),'▶ Відео','▶ Video');ab.type=vb.type='button';ab.addEventListener('click',()=>{stopDialog();const a=el('audio');a.controls=true;a.preload='metadata';a.src=s.audio;$('dialog-content').append(el('h2',null,s.title),a);openDialog(ab);a.play().catch(()=>{});});vb.addEventListener('click',()=>video(s.video,0,s.title,vb));actions.append(ab,vb);info.append(actions);card.append(preview,info);$('score-grid').append(card);});
 const photos=[...document.querySelectorAll('.photo-tile')];
 function showPhoto(i,button){photoIndex=(i+photos.length)%photos.length;stopDialog();const source=photos[photoIndex].querySelector('img'),img=el('img','viewer-img');img.src=source.src;img.alt=source.alt;const controls=el('div','viewer-controls'),prev=el('button',null,'‹'),next=el('button',null,'›');prev.type=next.type='button';prev.setAttribute('aria-label',tr('Попереднє фото','Previous photo'));next.setAttribute('aria-label',tr('Наступне фото','Next photo'));prev.addEventListener('click',()=>showPhoto(photoIndex-1));next.addEventListener('click',()=>showPhoto(photoIndex+1));controls.append(prev,el('span','viewer-counter',`${photoIndex+1} / ${photos.length}`),next);$('dialog-content').append(img,controls);box.dataset.kind='photo';if(button)openDialog(button);}
 photos.forEach((b,i)=>b.addEventListener('click',()=>showPhoto(i,b)));$('dialog-close').addEventListener('click',()=>box.close());box.addEventListener('close',()=>{stopDialog();box.dataset.kind='';document.body.classList.remove('photo-open');dialogOpener?.focus({preventScroll:true});});box.addEventListener('click',e=>{if(e.target===box){const r=box.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)box.close();}});document.addEventListener('keydown',e=>{if(box.open&&box.dataset.kind==='photo'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();showPhoto(photoIndex+(e.key==='ArrowRight'?1:-1));}});let touch=null;box.addEventListener('touchstart',e=>{if(box.dataset.kind==='photo'&&e.touches.length===1)touch=e.touches[0].clientX;},{passive:true});box.addEventListener('touchend',e=>{if(touch!==null&&box.dataset.kind==='photo'){const d=touch-e.changedTouches[0].clientX;touch=null;if(Math.abs(d)>50)showPhoto(photoIndex+(d>0?1:-1));}},{passive:true});
 document.addEventListener('languagechange',()=>{heading.textContent=heading.dataset[lang()];renderControls();});window.addEventListener('hashchange',()=>selectTab(location.hash.slice(1),false));choose(0);selectTab(location.hash.slice(1)||'listen',false);
})();
